#server:
#  port: 6000
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/AuthorizationServiceDB
#    password: root
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  application:
#    name: authentication-authorization-service
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${eureka_url:http://localhost:8761/eureka}